services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8333:8080"
    environment:
      - BASE_URL=http://localhost:8080/
    volumes:
      - ./searxng_settings:/etc/searxng
    restart: unless-stopped
